### ISSUE TITLE
sca object issues

### ISSUE THREAD

**Issue by ldliao** [voytekresearch/spectralCV#3]
- [x] load_spec(obj) needs to check whether the file is a data file or not
- [x] npz saves the KS vals but when you build load in the data and then compute the KS vals, the object doesn't have KS vals.
- [x] whether to add a data pointer/ include data in so we can plot data examples if wanted

**Comment by rdgao** [comment]
- decided to specify sca object filenames for files to load
- done
- gonna ignore that for all
